### ISSUE TITLE
Scraper 2.0.0 fails to scrape

### ISSUE THREAD

**Issue by kelson42** [openzim/gutenberg#172] opened 2023-02-21 04:58 UTC
https://farm.openzim.org/pipeline/f1dfacbc21b1214035793f36/debug

**Comment by benoit74** [comment] 2023-02-21 06:17
Looks like a release issue, this bug has been fixed in https://github.com/openzim/gutenberg/pull/168

The code displayed on the `stderr` is not anymore the one in `main` branch.

**Comment by rgaudin** [comment] 2023-02-21 06:35
indeed

**Comment by kelson42** [comment] 2023-02-21 06:39
Not usual, @rgaudin how have we managed this?

**Comment by rgaudin** [comment] 2023-02-21 07:04
I missed the last commit which unlike the others has not been merged in main.
I'll rewrite the tag

**Comment by rgaudin** [comment] 2023-02-21 07:06
My theory, am on my phone ; will check as soon as I arrive

**Comment by rgaudin** [comment] 2023-02-21 08:27
Wow, it's even weirder:

```
  File "/usr/local/lib/python3.11/site-packages/gutenberg2zim-2.0.0-py3.11.egg/gutenbergtozim/download.py", line 197, in <listcomp>
    (b.format.mime, b.format.images, b.format.pattern)
     ^^^^^^^^
AttributeError: 'BookFormat' object has no attribute 'format'
```

See how line `197` of `download.py` supposedly contains `b.format.mime` ?

[here's main](https://github.com/openzim/gutenberg/blob/main/gutenbergtozim/download.py#L196)

https://github.com/openzim/gutenberg/blob/524326b3792a82b683a97558214eb7c20e459136/gutenbergtozim/download.py#L196-L200

and [here's the tag](https://github.com/openzim/gutenberg/blob/v2.0.0/gutenbergtozim/download.py#L197)

https://github.com/openzim/gutenberg/blob/34fd1e7178d2e5a63c991054c481c10e2473f087/gutenbergtozim/download.py#L197

The problem is that both the tag and main points to the same commit but with a different ID…
Github [has the explanation](https://github.com/openzim/gutenberg/commit/34fd1e7178d2e5a63c991054c481c10e2473f087): “This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.” which is weird because I did that commit on main branch.

I'm not sure exactly what I did wrong ; retagging now

**Comment by rgaudin** [comment] 2023-02-21 08:53
Fixed

**Closed by rgaudin** 2023-02-21 08:53 UTC
Labels: bug
