### ISSUE TITLE
Add translation for Finnish

### ISSUE THREAD

**Issue by dattaz** [openzim/gutenberg#65] opened 2018-08-29 10:48 UTC
We want to have our interface for gutenberg project in Finnish.
File with strings to translate in json is here https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/l10n.py and you should add you locale here : https://github.com/openzim/gutenberg/blob/master/gutenbergtozim/export.py#L40

**Comment by kelson42** [comment] 2022-12-20 16:40
We should interface this scraper with Translatewiki.

**Comment by kelson42** [comment] 2022-12-20 16:42
Basically a duplicate of #56

**Closed** 2022-12-20 16:43 UTC
Labels: help wanted, good first issue
